// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ===================================================
// CÓDIGO GERADO AUTOMATICAMENTE PELO CLI DO FIREBASE
// ===================================================

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbNIlfrrdErH347mEos1gfZeMfP2bolQs',
    appId: '1:784207429650:web:9d854fe92c149e665858cb',
    messagingSenderId: '784207429650',
    projectId: 'devmobilefacuk',
    authDomain: 'devmobilefacuk.firebaseapp.com',
    storageBucket: 'devmobilefacuk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AdAu9vpmAyqa3XHajx4zvKZYBADBiCA',
    appId: '1:784207429650:android:fd873d9e73b4e9b25858cb',
    messagingSenderId: '784207429650',
    projectId: 'devmobilefacuk',
    storageBucket: 'devmobilefacuk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJwx88yOdceVRZDe9bdj6AJcD7-UMKLo4',
    appId: '1:784207429650:ios:d0a4056cdf7957115858cb',
    messagingSenderId: '784207429650',
    projectId: 'devmobilefacuk',
    storageBucket: 'devmobilefacuk.appspot.com',
    iosBundleId: 'com.example.projFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJwx88yOdceVRZDe9bdj6AJcD7-UMKLo4',
    appId: '1:784207429650:ios:d0a4056cdf7957115858cb',
    messagingSenderId: '784207429650',
    projectId: 'devmobilefacuk',
    storageBucket: 'devmobilefacuk.appspot.com',
    iosBundleId: 'com.example.projFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbNIlfrrdErH347mEos1gfZeMfP2bolQs',
    appId: '1:784207429650:web:088a14658d6ed87d5858cb',
    messagingSenderId: '784207429650',
    projectId: 'devmobilefacuk',
    authDomain: 'devmobilefacuk.firebaseapp.com',
    storageBucket: 'devmobilefacuk.appspot.com',
  );

}